test ingress deployment FE

diff --git a/.github/workflows/release.please.yml b/.github/workflows/release.please.yml
--- a/.github/workflows/release.please.yml
+++ b/.github/workflows/release.please.yml
@@ -284,90 +284,90 @@ jobs:
 ##          # docker push
 ##          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-  Deploy:
-    needs: [DryRunRelease, buildFE] #, buildBE]
-    if: |
-      always() &&
-      needs.DryRunRelease.result == 'success' &&
-      (needs.buildFE.result == 'success' || needs.buildFE.result == 'skipped') 
-#      && (needs.buildBE.result == 'success' || needs.buildBE.result == 'skipped')
-    name: Deploy
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-    outputs:
-      IMAGETAG: ${{ steps.imagetag.outputs.IMAGETAG }}
-    steps:
-      - uses: actions/checkout@v3.0.2
-        with:
-          ref: main
-          fetch-depth: '0'
-
-      - name: Check Input Version
-        if: ${{ github.event.inputs.version != '' }}
-        id: checkver
-        run: |
-          set -x
-          version="${{ github.event.inputs.version }}"
-          echo "==> Version: $version"
-          if [ $(git tag -l "$version" | wc -l) -gt 0 ]; then
-            echo "Version $version exists. Input accepted."
-          else
-            echo "Version $version doesn't exist. INVALID INPUT."
-            exit 1
-          fi
-          set +x
-
-      - uses: azure/setup-kubectl@v2.1
-        with:
-          version: 'v1.23.6' # default is latest stable
-        id: install
-
-      - name: Configure AWS credentials for ECR
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Configure AWS credentials for K8S
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          role-session-name: Git
-          role-duration-seconds: 3600
-
-      - name: Setup Kubeconfig
-        run: |
-          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}
-
-      - name: Setup Image TAG
-        id: imagetag
-        run: |
-          if [ "${{ github.event.inputs.version }}" = "" ]; then
-            echo "::set-output name=IMAGETAG::$(echo ${{needs.DryRunRelease.outputs.version}} )"
-          else
-            echo "::set-output name=IMAGETAG::$(echo ${{ github.event.inputs.version }} )"
-          fi
-
-      - name: Setup 'fe-piattaforma' deployment.tmp.yaml
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: fe-piattaforma
-          IMAGE_TAG: ${{ steps.imagetag.outputs.IMAGETAG }}
-        run: |
-          cd ${{ github.workspace }}/fe-piattaforma/k8s
-          export ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY
-          export IMAGE_TAG=$IMAGE_TAG
-          envsubst < deployment.tmp.yml >> ${{ github.workspace }}/deployment.yml
+#####  Deploy:
+#####    needs: [DryRunRelease, buildFE] #, buildBE]
+#####    if: |
+#####      always() &&
+#####      needs.DryRunRelease.result == 'success' &&
+#####      (needs.buildFE.result == 'success' || needs.buildFE.result == 'skipped') 
+######      && (needs.buildBE.result == 'success' || needs.buildBE.result == 'skipped')
+#####    name: Deploy
+#####    runs-on: ubuntu-latest
+#####    defaults:
+#####      run:
+#####        shell: bash
+#####    outputs:
+#####      IMAGETAG: ${{ steps.imagetag.outputs.IMAGETAG }}
+#####    steps:
+#####      - uses: actions/checkout@v3.0.2
+#####        with:
+#####          ref: main
+#####          fetch-depth: '0'
+#####
+#####      - name: Check Input Version
+#####        if: ${{ github.event.inputs.version != '' }}
+#####        id: checkver
+#####        run: |
+#####          set -x
+#####          version="${{ github.event.inputs.version }}"
+#####          echo "==> Version: $version"
+#####          if [ $(git tag -l "$version" | wc -l) -gt 0 ]; then
+#####            echo "Version $version exists. Input accepted."
+#####          else
+#####            echo "Version $version doesn't exist. INVALID INPUT."
+#####            exit 1
+#####          fi
+#####          set +x
+#####
+#####      - uses: azure/setup-kubectl@v2.1
+#####        with:
+#####          version: 'v1.23.6' # default is latest stable
+#####        id: install
+#####
+#####      - name: Configure AWS credentials for ECR
+#####        uses: aws-actions/configure-aws-credentials@v1
+#####        with:
+#####          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#####          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#####          aws-region: ${{ secrets.AWS_REGION }}
+#####
+#####      - name: Login to Amazon ECR
+#####        id: login-ecr
+#####        uses: aws-actions/amazon-ecr-login@v1
+#####
+#####      - name: Configure AWS credentials for K8S
+#####        uses: aws-actions/configure-aws-credentials@v1
+#####        with:
+#####          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#####          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#####          aws-region: ${{ secrets.AWS_REGION }}
+#####          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#####          role-session-name: Git
+#####          role-duration-seconds: 3600
+#####
+#####      - name: Setup Kubeconfig
+#####        run: |
+#####          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_CLUSTER }}
+#####
+#####      - name: Setup Image TAG
+#####        id: imagetag
+#####        run: |
+#####          if [ "${{ github.event.inputs.version }}" = "" ]; then
+#####            echo "::set-output name=IMAGETAG::$(echo ${{needs.DryRunRelease.outputs.version}} )"
+#####          else
+#####            echo "::set-output name=IMAGETAG::$(echo ${{ github.event.inputs.version }} )"
+#####          fi
+#####
+#####      - name: Setup 'fe-piattaforma' deployment.tmp.yaml
+#####        env:
+#####          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#####          ECR_REPOSITORY: fe-piattaforma
+#####          IMAGE_TAG: ${{ steps.imagetag.outputs.IMAGETAG }}
+#####        run: |
+#####          cd ${{ github.workspace }}/fe-piattaforma/k8s
+#####          export ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY
+#####          export IMAGE_TAG=$IMAGE_TAG
+#####          envsubst < deployment.tmp.yml >> ${{ github.workspace }}/deployment.yml
 
 #      - name: Setup 'ms-ente' deployment.tmp.yaml
 #        env:
@@ -441,13 +441,13 @@ jobs:
 #          envsubst < deployment.tmp.yml
 #          cat deployment.tmp.yml >> ${{ github.workspace }}/deployment.yml
 
-      - name: Deploy
-        run: |
-          cd ${{ github.workspace }}
-          echo "===DEPLOYMENT FILE==="
-          cat deployment.yml
-          echo "====================="
-          kubectl apply -f deployment.yml
+#####      - name: Deploy
+#####        run: |
+#####          cd ${{ github.workspace }}
+#####          echo "===DEPLOYMENT FILE==="
+#####          cat deployment.yml
+#####          echo "====================="
+#####          kubectl apply -f deployment.yml
 
 ##      - name: Check fe-piattaforma Deploy
 ##        id: fe-piattaforma
@@ -475,7 +475,7 @@ jobs:
 
   RepoUpdate:
     if: ${{ github.event.inputs.version == '' }}
-    needs: [DryRunRelease, Deploy]
+    needs: [DryRunRelease] #, Deploy]
     name: Repo Update
     runs-on: ubuntu-latest
     defaults:
